### ISSUE TITLE
Feature Request: Add Status Badge support 

### ISSUE THREAD

**Issue by haysclark** [jenkins-x/jx-pipelines-visualizer#110]
It would be great to add _Status Badge_ support so that JX3 users could add Build Status Shield.IO badges to their GitHub repos.

Example:
![Build Status](https://img.shields.io/endpoint?url=https%3A%2F%2Fstatusbadge-jx.jenkins-x.live%2Fjx)

In JX2, _Status Badge_ support could be added via [The Jenkins X Status Badge App](https://github.com/jenkins-x-apps/jx-app-statusbadge). Unfortunately, this app does not work with JX3.

**Comment by haysclark** [comment]
@jstrachan Suggested I post this Feature Request in the `jenkins-x/jx-pipelines-visualizer`. - [Slack thread](https://kubernetes.slack.com/archives/C9MBGQJRH/p1619459368285300)

**Comment by vbehar** [comment]
good idea, shouldn't be too hard to implement. the old code is here: https://github.com/jenkins-x/status-badge
