### ISSUE TITLE
Failed to execute 'fetch' on 'Window'

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx-pipelines-visualizer#113]
I've just seen this issue for the first time using the visualiser:

```
TypeError: Failed to execute 'fetch' on 'Window': Request cannot be constructed from a URL that includes credentials: /jstrachan/node-example/master/1/logs
```

for pipelines which have logs written to a bucket. The `View raw logs` link works perfectly though & live logs work too.

I wonder if this is a client side JS issue with how the code fetches + renders non-live logs?

## Workaround

* Click the `View raw logs` button for now to see the logs if you see this error in the dashboard

* Another workaround is to open the dashboard URL with a full URL without the `http://admin:pwd@` prefix then things work fine

**Comment by thecooldrop** [comment]
How can this issue be recreated?

**Comment by jstrachan** [comment]
if you use `jx dash` you'll get the dashboard UI. Then for pipelines that have completed (and so have their logs in long term storage) if you click on those pipelines, no logs will appear and instead you get: 

```
TypeError: Failed to execute 'fetch' on 'Window': Request cannot be constructed from a URL that includes credentials: /jstrachan/node-example/master/1/logs
```

If you then copy/paste the entire URL and remove the `admin:pwd@` text from your address bar and open a brand new browser window it works fine

**Comment by jstrachan** [comment]
fixed by https://github.com/jenkins-x/jx-pipelines-visualizer/pull/116
