### ISSUE TITLE
javascript error while getting live logs

### ISSUE THREAD

**Issue by vbehar** [jenkins-x/jx-pipelines-visualizer#126]
when viewing live logs at the beginning of the pipeline, the UI was blocked after displaying the first line of log. The others came in, but due to a javascript error, they were not displayed.

the JS error is:

```
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': 'tr[data-step=][data-is-parent-step=true]' is not a valid selector.
    at getParentStep (http://localhost:8080/static/pipeline/index.js?v=dev:19:44)
    at repeatOften (http://localhost:8080/static/pipeline/index.js?v=dev:253:32)
```

screenshot of the UI and the error:

<img width="1440" alt="Capture d’écran 2021-06-01 à 10 29 31" src="https://user-images.githubusercontent.com/6251/120292231-6d6a6580-c2c4-11eb-9c40-c46232e8fce9.png">

screenshot of the DOM:

<img width="574" alt="Capture d’écran 2021-06-01 à 10 34 08" src="https://user-images.githubusercontent.com/6251/120292837-ed90cb00-c2c4-11eb-8132-94e3a0cb0deb.png">

while it should be something like the following (taken from a different pipeline/page without the bug):

<img width="845" alt="Capture d’écran 2021-06-01 à 10 54 42" src="https://user-images.githubusercontent.com/6251/120295827-d0a9c700-c2c7-11eb-8d92-bd947cb8665c.png">

**Comment by vbehar** [comment]
cc @florianorpeliere an interesting one ;-)

**Comment by florianorpeliere** [comment]
Indeed, there is an error in the selector `tr[data-step=]` (we need something after the `=`).
I will make a PR to fix that 😉

**Comment by vbehar** [comment]
after a quick look, I think it's because the `currentStep` is empty here https://github.com/jenkins-x/jx-pipelines-visualizer/blob/master/web/static/pipeline/index.js#L253
and also we're missing some quotes here https://github.com/jenkins-x/jx-pipelines-visualizer/blob/master/web/static/pipeline/index.js#L185 if the `currentStep` is empty

but it doesn't explain why the `currentStep` is empty

**Comment by vbehar** [comment]
oh, in fact it's empty at the beginning, before printing the logs of the first container. when it's waiting for the 1st container to start. maybe we just need a few `if(currentStep){}`... ;-)
