### ISSUE TITLE
link to owner/repo/branch on the pipeline/log view page

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx-pipelines-visualizer#2]
loving the UI! 

when viewing the pipeline page...
<img width="982" alt="dashboard-jx_34_66_77_190_nip_io_jstrachan_nodey532_PR-3_1" src="https://user-images.githubusercontent.com/30140/95432786-053ace00-0947-11eb-836b-aa0b8d76b38f.png">

it might be nice to show a breadcrumb bar with links rather than the PipelineActivity name?

e.g.

```
Pipelines > owner > repo > branch #1 
```

and each breadcrumb could then be a link to all or filter pipelines by that term (e.g. by owner, owner + repo, owner + repo + branch) etc.

e.g. links could be:

```
Pipelines => "/"
owner => "/owner"
repo => "/owner/repo"
branch => "/owner/repo/branch"
```

(like clicking on those links on the home page)

**Comment by vbehar** [comment]
yes! I think that @florianorpeliere already has something in mind for this ;-)
