### ISSUE TITLE
view builds in reverse order

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx-pipelines-visualizer#20]
when viewing all the builds for a given repository/branch it would be nice to sort them in reverse order so that the latest builds appear first at the top.

e.g. the builds page would show...

* 5 
* 4 
* 3
* 2 
* 1

it might be nice to use a badge CSS for build numbers too maybe? Or the Jenkins convention of prefixing them with "#" maybe?

**Comment by AshwinKul28** [comment]
Hello, I would like to work on it using bash scripting. But where can I get a list of builds with its date or time of build? Can you please assign it to me?

**Comment by jstrachan** [comment]
@AshwinKul28 its maybe easier to modify the Pipelines function to return the pipelines in newest order first (i.e. biggest build number) so that templates like this render most recent pipelines first: https://github.com/jenkins-x/jx-pipelines-visualizer/blob/master/web/templates/home.tmpl#L49

**Comment by vbehar** [comment]
yes, in fact these pages are horrible, I'll rewrite them to use the same UI as the main page, but with a "filtered" scope - and less columns, to avoid printing useless data
