### ISSUE TITLE
show steps in a stage in the pipelines view

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx-pipelines-visualizer#3]
the PipelineActivity structure uses a Stage and then has individual steps within a stage; so its a kinda 2 level tree.

e.g. this pipeline...
<img width="982" alt="dashboard-jx_34_66_77_190_nip_io_jstrachan_nodey532_PR-3_1" src="https://user-images.githubusercontent.com/30140/95433705-3798fb00-0948-11eb-8600-19a17e96ff5c.png">

looks like this in Octant:
<img width="1188" alt="Octant" src="https://user-images.githubusercontent.com/30140/95433732-441d5380-0948-11eb-8c48-46cc6d1d6c30.png">

so it might be nice to iterate the steps inside the stage too?

**Comment by vbehar** [comment]
btw this has been done in https://github.com/jenkins-x/jx-pipelines-visualizer/pull/65
