### ISSUE TITLE
nav bar/breadcrumbs should have a solid background

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx-pipelines-visualizer#31]
@florianorpeliere many thanks for all of your recent improvements; loving them!

now that the nav bar/breadcrumbs stay as the window scrolls with build logs, they have a transparent background so it can look odd if the text is over the top of a log line (see below).

I wonder if we can make the nav bar/breadcrumb be a separate CSS div that doesn't scroll - or has a solid white background color or something? 

<img width="1226" alt="jx-log" src="https://user-images.githubusercontent.com/30140/97170478-aae1a000-1783-11eb-8ec4-97c4b926b18b.png">

**Comment by florianorpeliere** [comment]
Hi @jstrachan,
Thanks a lot 😄 
Indeed, it's weird because I don't have this behavior.

![Screenshot 2020-10-26 at 13 28 00](https://user-images.githubusercontent.com/7460283/97172287-1f6e0c00-178f-11eb-9d45-efc794c5814d.png)

I'm going to check now.
Sorry for that.

**Comment by florianorpeliere** [comment]
@jstrachan
I checked again and even in localhost, I didn't have this behavior.

![Screenshot 2020-10-26 at 14 28 34](https://user-images.githubusercontent.com/7460283/97178378-acb55e80-1797-11eb-907c-882aeea2c560.png)

Can you give me more information please ? Your browser ?

**Comment by jstrachan** [comment]
whats wacky is - I don't have this behaviour any more! I guess it was either a browser caching issue or maybe my browser didn't load a CSS properly or something! 

sorry for the noise!
