### ISSUE TITLE
helm chart ingress's syntax is incorrect

### ISSUE THREAD

**Issue by vincenthodicq** [jenkins-x/jx-pipelines-visualizer#39]
When configuring tls with the helm chart, if b64encodedCertificate & b64encodedCertificateKey values, host is not added to tls section.

And if we use an existing secret for tls, templating the chart failed due to absence of b64encodedCertificate & b64encodedCertificateKey.

And last issue with ingress, indentation is not good when using tls
```apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: RELEASE-NAME-jx-pipelines-visualizer
  labels:
    app.kubernetes.io/name: jx-pipelines-visualizer
    app.kubernetes.io/instance: "RELEASE-NAME"
    helm.sh/chart: jx-pipelines-visualizer-0.0.52
    app.kubernetes.io/version: "0.0.52"
    app.kubernetes.io/managed-by: "Helm"
spec:
  rules:
  - host: pipelines.beyond-monitoring.com
    http:
      paths:
      - backend:
          serviceName: RELEASE-NAME-jx-pipelines-visualizer
          servicePort: http
  tls:
  - secretName: RELEASE-NAME-jx-pipelines-visualizer-tls-embedded---
apiVersion: v1
data:
  auth: XXX
...
```

**Comment by vincenthodicq** [comment]
I can work on a fix on the chart and make a PR

**Comment by vbehar** [comment]
yes, that would be great, thanks!

**Comment by vincenthodicq** [comment]
Ok, i will push the change on friday

**Comment by vincenthodicq** [comment]
Hi @vbehar 

I am getting a 403 http error when pushing my branch to Github. Any clues?
