### ISSUE TITLE
Unable to view pipeline logs from jx dashboard

### ISSUE THREAD

**Issue by anilkumarpasupuleti** [jenkins-x/jx-pipelines-visualizer#50]
cloud provider: eks
k8s version: 1.17
Chart version: jx-pipelines-visualizer-0.0.60

We are storing the logs to s3 bucket. We were able to view the logs for pr and release builds from the dashboard, but after upgrading to beta(which upgraded the jx-pipelines-visualizer chart to 0.0.60) failed to view the logs from dashboard. 

current behavior: Unable to view the logs for pr and release builds from dashboard
Actual behavior: Suppose to view log for pr and release builds from dashboard

**Comment by vbehar** [comment]
closing, as this was a build controller issue (solved in slack)
