### ISSUE TITLE
Feature request: Add an option to access or download raw logs

### ISSUE THREAD

**Issue by ankitm123** [jenkins-x/jx-pipelines-visualizer#52]
It would be awesome to have an option to view and download raw logs - one without fancy HTML, similar to what jenkins/circleCI provide.

**Comment by vbehar** [comment]
Yes, the endpoint already exists, if you go to `/$org/$repo/$branch/$build/logs` (just add `/logs` to the build logs URL). but we should definitely add a link to this URL to download the raw logs

**Comment by florianorpeliere** [comment]
@ankitm123 Hey :) 
Do you work on it ? If you want, I could do it ;) 
Let me know.

**Comment by ankitm123** [comment]
> If you want, I could do it ;)

Go ahead :)
