### ISSUE TITLE
No logs shown for build

### ISSUE THREAD

**Issue by jmmk** [jenkins-x/jx-pipelines-visualizer#55]
When checking the logs for a build, the page simply shows `Please wait while we get logs...`, but there is no network activity and the logs never load.

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/1122242/103663911-a124a780-4f3f-11eb-8383-f1c5ff87840f.png">

When running `jx get build logs` for the same build, I receive the following error:

`error: the build pods for this build have been garbage collected and the log was not found in the long term storage bucket`

I would expect the UI to surface the same error message

**Comment by florianorpeliere** [comment]
Hi @jmmk 
Indeed, the UI should display an error message. I will correct this 😉.
Thanks.

**Comment by vbehar** [comment]
@jmmk ok it's been fixed in 1.0.2
